import { MachineMaster, MachineRuleDetail } from "./types";

// ------------------------------------------------------------------
// このファイルは「機種マスタ」「機種ルール詳細」シートの内容を
// そのままハードコードしたダミーデータです。
// 本番では lib/sheets.ts が Google Sheets API から同じ形に整形して返すため、
// UI・判定ロジック側はこのデータ構造だけを見ていれば動くようにしてあります。
// （= このファイルを丸ごと削除して sheets.ts に差し替えても他のコードは壊れない）
// 最終確認日: 2026-06-23
// ------------------------------------------------------------------

export const machineMasters: MachineMaster[] = [
  {
    machineId: "hokutonoken_2023",
    machineName: "スマスロ北斗の拳",
    maker: "サミー",
    releaseDate: "2023-04-03",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: false,
    baseQuitTiming:
      "BB終了後、内部状態（天国/本前兆の可能性）を確認のうえヤメ時を判断",
    lastConfirmedAt: "2026-06-23",
    sourceMemo: "1geki.jp / slogati.com / slobase.com / nana-press.com 等",
    notes: "天井が300G/777G/800Gで短縮抽選される独自仕様。北斗ブランドの王道機",
  },
  {
    machineId: "hokutonoken_tensei2",
    machineName: "スマスロ北斗の拳 転生の章2",
    maker: "サミー",
    releaseDate: "要確認",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "AT終了後即ヤメが基本。ただし残りカウンターが多い場合は継続判断",
    lastConfirmedAt: "2026-06-23",
    sourceMemo: "1geki.jp / slogati.com / slobase.com / nana-press.com 等",
    notes:
      "ゲーム数の代わりに独自カウンター「あべし」を使用する点に注意。①と同シリーズで比較しやすい",
  },
  {
    machineId: "bakemonogatari_2025",
    machineName: "スマスロ化物語",
    maker: "サミー",
    releaseDate: "2025-12-08",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: false,
    payoutSetting1: 97.4,
    payoutSetting6: 112.4,
    baseQuitTiming:
      "AT（俙時間）終了後、解呪連モードや高確状態を確認してヤメ時を判断",
    lastConfirmedAt: "2026-06-23",
    sourceMemo: "1geki.jp / slogati.com / slobase.com / nana-press.com 等",
    notes:
      "設置約12,000台/4,769店舗と導入実績が高い。ヤメ時の判断要素が多い複合型",
  },
  {
    machineId: "tokyoghoul_2025",
    machineName: "L東京喰種",
    maker: "スパイキー",
    releaseDate: "2025-02-03",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: false,
    baseQuitTiming:
      "AT（東京喰種咬）終了後、特化ゾーンや赫眼状態の有無を確認してヤメ時を判断",
    lastConfirmedAt: "2026-06-23",
    sourceMemo: "1geki.jp / slogati.com / slobase.com / nana-press.com 等",
    notes: "天井が2種類（CZ間/AT間）あるシンプル寄りの天井型。チェリー高確の赫眼状態が特徴",
  },
  {
    machineId: "enenshouboutai2_2026",
    machineName: "Lパチスロ炎炎ノ消防隊2",
    maker: "SANKYO",
    releaseDate: "2026-02-02",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: false,
    payoutSetting1: 97.7,
    payoutSetting6: 114.9,
    baseQuitTiming:
      "伝導者の罠終了後88G+前兆消化を確認してヤメ。炎炎ループ絡みは要注意",
    lastConfirmedAt: "2026-06-23",
    sourceMemo: "1geki.jp / slogati.com / slobase.com / nana-press.com 等",
    notes:
      "ボーナス間/炎炎ループ間の2段階天井+スルー天井を持つ複数ゾーン型の典型例",
  },

  // --- ここから2026-07-05リサーチ分（ホール主要機種の追加） ---
  {
    machineId: "tokyorevengers_2025",
    machineName: "スマスロ東京リベンジャーズ",
    maker: "サミー",
    releaseDate: "2025-09-08",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "AT/ボーナス終了後、サブ液晶のセリフを確認し、赤セリフでなければ即ヤメが基本",
    lastConfirmedAt: "2026-07-05",
    sourceMemo: "slopachi-quest.com / p-town.dmm.com / chonborista.com / note(きこりブログ) 等",
    notes:
      "周期ポイント制（最大500pt×6周期）とAT間天井、ボーナススルー天井の3種類の天井を持つ複合型。導入台数約20,000台と大型導入",
  },
  {
    machineId: "shinonimusya3_2025",
    machineName: "スマスロ新鬼武者3",
    maker: "エンターライズ（レオスター）",
    releaseDate: "2025-10-06",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "AT終了後は基本即ヤメ。ただし上位AT「真蒼剣RUSH」終了後は次回1周期目のAT当選が濃厚なため継続価値あり",
    lastConfirmedAt: "2026-07-05",
    sourceMemo: "slopachi-quest.com / nana-press.com / chonborista.com / p-world.co.jp 等",
    notes:
      "ゲーム数天井（1000G+α）と周期天井（バッサリポイント、最大6周期・設定変更後4周期）の複合型。350G/550G付近にゾーンあり",
  },
  {
    machineId: "gundamseed_2025",
    machineName: "Lパチスロ 機動戦士ガンダムSEED",
    maker: "ビスティ",
    releaseDate: "2025-05-07",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: false,
    hasOwnPoint: true,
    baseQuitTiming:
      "CZ/ST終了後は基本即ヤメ。ただしボーナス中に宿命ポイントが貯まっている場合は宿命ゾーン到達まで継続価値あり",
    lastConfirmedAt: "2026-07-05",
    sourceMemo: "chonborista.com / p-town.dmm.com / nankaikoya.jp / haienakun.com 等",
    notes:
      "CZ天井（777G）とST天井（1280G）の2段階天井。設定変更時・ST駆け抜け時は750Gに短縮。明確なゾーン演出は未確認のため要継続調査",
  },
  {
    machineId: "magireco_2025",
    machineName: "スマスロ マギアレコード 魔法少女まどか☆マギカ外伝",
    maker: "ミズホ",
    releaseDate: "2025-04-07",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "ボーナス/AT終了後は基本1Gヤメ。ただしみたまボーナス終了後は平均15Gヤメが目安",
    lastConfirmedAt: "2026-07-05",
    sourceMemo: "slopachi-quest.com / 1geki.jp / enaiki.com / note(シオン期待値研究所) 等",
    notes:
      "ボーナス間天井は独自ポイント制（穢れシステム）。200pt/400pt/600ptにゾーンあり。設置店舗数4,748店舗と導入実績が高い",
  },
  {
    machineId: "milliongod_kiseki_2026",
    machineName: "スマスロ ミリオンゴッド-神々の軌跡-",
    maker: "ミズホ",
    releaseDate: "2026-04-20",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: false,
    baseQuitTiming:
      "AT「ゴッドゲーム（GG）」終了後36G以内はGG引き戻しの可能性があるため、必ずフォローしてからヤメる",
    lastConfirmedAt: "2026-07-05",
    sourceMemo: "nana-press.com / slopachi-quest.com / p-world.co.jp / 1geki.jp 等",
    notes:
      "天井ゲーム数は510G/1000G/1480Gの3種類。設定変更時は510Gか1000Gに短縮。2026年6月時点の稼働ランキングで上位の人気機種",
  },

  // --- ここから2026-07-06リサーチ分（バッチ2） ---
  {
    machineId: "kyokosuiri_2026",
    machineName: "L虚構推理",
    maker: "ディ・ライト",
    releaseDate: "2026-04-06",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "AT終了後、有利区間ランプが消灯していればヤメ。虚構連モード滞在中は転落せず50G経過したら虚構真偽突入濃厚のため50Gを目安にフォロー",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "slopachi-quest.com / p-town.dmm.com / p-world.co.jp / enaiki.com 等",
    notes:
      "通常時（虚構真偽間）最大1000G消化で天井。300G以降は設定差が大きい。設定変更時は300Gまたは700Gに短縮。虚構連モード（ショート/ミドル/ロング）という独自の連チャンモード制が特徴",
  },
  {
    machineId: "koukakukidoutai_2026",
    machineName: "スマスロ攻殻機動隊",
    maker: "サミー",
    releaseDate: "2026-02-02",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "AT終了後は基本即ヤメ。ただし通常Dに滞在している場合は150G+αでCZ当選するためフォロー推奨。白の境界失敗後はCZ天井が400G+αに短縮されるため継続推奨",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "slopachi-quest.com / p-world.co.jp / note(のりへい) / slobase.jp 等",
    notes:
      "CZ間天井（550G+α）とAT間天井（999G+α）の2段階天井。設定変更時はCZ間350G+α・AT間699G+αに短縮され、設定1でも機械割100%超。殲滅ポイント（150pt到達で殲滅ゾーン）という独自ポイント制あり",
  },
  {
    machineId: "gundam_unicorn_kakusei_2026",
    machineName: "Lパチスロ 機動戦士ガンダムユニコーン 覚醒DRIVE",
    maker: "ビスティ",
    releaseDate: "2026-04-20",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: false,
    baseQuitTiming:
      "AT終了後は前兆確認、または100Gのゾーンを過ぎてからヤメ。上位AT『覚醒HYPER -Over The Rainbow-』終了後（覚醒の光失敗後）はスタンバイレベルMAXが引き継がれ次回リプレイでCZ以上が確約されるため即ヤメ厳禁",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "slopachi-quest.com / chonborista.com / nana-press.com / p-world.co.jp 等",
    notes:
      "CZ天井（800G+α）とAT天井（1400G+α）の2段階天井に加え、CZ6スルー天井（7回目のCZで直接ボーナス当選）を搭載。設定変更時はCZ400G+α・AT1000G+αに短縮",
  },
  {
    machineId: "yoshimune_2025",
    machineName: "L吉宗",
    maker: "大都技研",
    releaseDate: "2025-04-21",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: false,
    payoutSetting1: 97.8,
    payoutSetting6: 112.0,
    baseQuitTiming:
      "ボーナス終了後193G（天国の前兆）まで回してヤメ。ただし鷹狩りからのボーナス当選・松からのボーナス当選・裏鷹狩り失敗後は天国濃厚なため即ヤメ厳禁",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "chonborista.com / slopachi-quest.com / amuse-p.com / tsuranuki-method.com 等",
    notes:
      "純増約7.1枚/Gの高純増ボーナス機。ボーナス間天井999G、ボーナス後の天国モード移行で天井193Gに短縮。1G連2回獲得で期待値約3600枚の裏鷹狩りへ",
  },
  {
    machineId: "valvrave2_2025",
    machineName: "Lパチスロ 革命機ヴァルヴレイヴ2",
    maker: "SANKYO",
    releaseDate: "2025-11-04",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "BB/RB終了後は基本1Gヤメ。ただしAT（革命RUSH）終了後は66G間引き戻しの可能性があるため確認してからヤメる",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "slopachi-quest.com / chonborista.com / p-world.co.jp / nana-press.com 等",
    notes:
      "ボーナス・AT間天井（1500G+α）、CZ間天井（999G+α）、周期天井（最大6周期）、決戦ボーナススルー天井の4種類の天井を持つ複合型。ヴヴヴシリーズの正当後継機で導入台数が多い",
  },
  {
    machineId: "superblackjack_2025",
    machineName: "スマスロスーパーブラックジャック",
    maker: "セブンリーグ（山佐ネクスト）",
    releaseDate: "2025-02-03",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: false,
    baseQuitTiming:
      "BIG終了後は最低30G間リオチャンス高確率に滞在するため即ヤメ厳禁。RB当選時は通常時ゲーム数を引き継ぐため、天井が近い場合やRBスルー回数が4回に近い場合はBIG当選まで続行",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "slopachi-quest.com / amuse-p.com / haienakun.com / 1geki.jp 等",
    notes:
      "ゲーム数天井（999G+α）とRB4連続スルーで次回BIG確定という2種類の救済に加え、スイカ回数天井（規定回数でストックタイム直撃）を搭載。4号機の人気シリーズの正統後継機",
  },
  {
    machineId: "sao2_2026",
    machineName: "スロット ソードアート・オンラインII",
    maker: "パオン・ディーピー（大都技研グループ）",
    releaseDate: "2026-06-08",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: false,
    baseQuitTiming:
      "AT終了後50Gの引き戻しゾーンを消化してから判断するのが基本。初回の上位CZ失敗後はCZ天井が256G+αに短縮されるため続行価値あり",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "slopachi-quest.com / p-town.dmm.com / p-world.co.jp / note(蒼天井) 等",
    notes:
      "AT間天井（1200G）とCZ間天井（499G+α、液晶800G）の2段階天井。内部モード（通常A/B/C/D・天国）でCZ当選ペースが管理される。2026年6月導入後、全国稼働トップクラスの人気機種",
  },
  {
    machineId: "kabaneri2_2026",
    machineName: "スマスロ 甲鉄城のカバネリ 海門決戦",
    maker: "サミー",
    releaseDate: "2026-03-02",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "ST終了後、カバネポイントが溜まっていなければ基本即ヤメ。ST駆け抜け後・景之ST終了後はサブ液晶の背景が桜/海門城に変化していれば次回ボーナスまでフォロー",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "slopachi-quest.com / p-town.dmm.com / p-world.co.jp / 1geki.jp / nana-press.com 等",
    notes:
      "ゲーム数天井（996G+α）と周期天井（最大6周期）の2種類。1周期目150G・2周期目300Gで自動到達する独自の周期システム。設定変更時・ST駆け抜け後・景之ST後は596G+α・4周期に短縮",
  },
  {
    machineId: "karakurisaakasu_2023",
    machineName: "パチスロ からくりサーカス",
    maker: "SANKYO",
    releaseDate: "2023-07-03",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: false,
    baseQuitTiming: "幕間チャンス後1G回してワイプ画面（規定ゲーム数示唆）を確認してからヤメ",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "chonborista.com / p-town.dmm.com / p-world.co.jp / haienakun.com / altema.jp 等",
    notes:
      "ゲーム数天井1200G。前回液晶1100G以上での当選なら次回天井が最大300Gに短縮。上位AT終了後は約40%で天国移行（天井100G）。導入台数が多く解析情報も豊富な定番機",
  },
  {
    machineId: "kinnikuman_7akuma_2023",
    machineName: "スマスロ キン肉マン 7人の悪魔超人編",
    maker: "山佐",
    releaseDate: "2023-08-07",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "天井到達率が高くゾーンでの当選率上昇もほぼ無いため、示唆がなければAT終了後は原則即ヤメ",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "chonborista.com / slopachi-quest.com / note(たられば) / itikatu.jp 等",
    notes:
      "超人パワー1000万到達（実ゲーム数平均600G前後）でAT当選。モードにより天井ゲーム数が変動（モードA1000G/モードB900G/チャンス300G）。設定変更後はチャンスモード選択率が約25%に優遇",
  },
  {
    machineId: "godeater_resurrection_2024",
    machineName: "スマスロ ゴッドイーター リザレクション",
    maker: "セブンリーグ（山佐ネクスト）",
    releaseDate: "2024-07-22",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: false,
    baseQuitTiming:
      "AT終了後1G回して状態を確認してからヤメが基本。バカンスモード移行時・逆鱗ハンニバル討伐戦敗北時・有利区間差枚+1000枚以上の場合は100G+αフォロー",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "chonborista.com / slopachi-quest.com / amuse-p.com / note(きこり) / haienakun.com 等",
    notes:
      "ゲーム数天井1000G+α（100/200/300/450/600/750/1000Gの7種の振り分け）。設定変更後は600G+αに短縮。導入台数約10,000台",
  },
  {
    machineId: "zenigata5_2025",
    machineName: "L主役は銭形5",
    maker: "オリンピア（平和）",
    releaseDate: "2025-10-06",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "ST終了後は基本即ヤメ。ただしST後80G以内にボーナス当選すれば前回の逮捕状況を引き継いで復帰するため、状況次第でフォロー価値あり",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "p-world.co.jp / slopachi-quest.com / chonborista.com / note(けんけん) 等",
    notes:
      "ゲーム数天井1250G+α（設定変更後850G+α）。150G/350G/550Gにゾーンあり。捜査ポイント（0pt到達でCZ「逮捕チャレンジ」）という独自ポイント制",
  },
  {
    machineId: "seiya_kaiou_2024",
    machineName: "スマスロ 聖闘士星矢 海皇覚醒 CUSTOM EDITION",
    maker: "SANYO（サンスリー）",
    releaseDate: "2024-06-03",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "CZ/AT終了後5G回して前兆の有無を確認してヤメが基本。継続率70%以上のCZ失敗時や特定の示唆演出が出た場合は即ヤメ厳禁",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "chonborista.com / slopachi-quest.com / note(たられば) / enaiki.com / itikatu.jp 等",
    notes:
      "ゲーム数天井999G（600Gに期待度50%の仮天井あり）。設定変更時・SR終了時は536G+αに短縮。GBスルー天井（8スルー後9回目で確定）と不屈ポイント（50pt到達でCZ突破確定）の独自システムを搭載",
  },
  {
    machineId: "tekken6_2026",
    machineName: "スマスロ鉄拳6",
    maker: "山佐",
    releaseDate: "2026-01-05",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "AT終了後は引き戻し状態（99pt以内）になっているか確認してからヤメ。即ヤメされている台の引き戻し＆100ptでの天国も判別要素",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "slopachi-quest.com / p-town.dmm.com / chonborista.com / 1geki.jp 等",
    notes:
      "鉄拳ポイント天井（モードにより変動、最大500pt+α）。設定変更時は最大500pt+αに短縮。100pt/300pt/500ptにゾーンあり。7種類の内部モードで天井・ゾーンが変化する複合型",
  },
  {
    machineId: "toaru_railgun2_2025",
    machineName: "スマスロ とある科学の超電磁砲2",
    maker: "藤商事",
    releaseDate: "2025-11-04",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: false,
    baseQuitTiming:
      "AT終了後、100Gのゾーンは約25%でCZ天井のためフォロー価値あり。高確状態（超電磁砲コインが成立しやすい）ならフォロー推奨",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "slopachi-quest.com / chonborista.com / haienakun.com / note(たられば) / p-world.co.jp 等",
    notes:
      "ゲーム数天井999G+α（設定変更後699G+αに短縮）。モード別天井（通常A999G/B・C699G/D299G/E199G）で変動。AT後500Gのゾーンが強い（期待度約40%）",
  },
  {
    machineId: "osubancho4_2024",
    machineName: "L押忍！番長4",
    maker: "大都技研",
    releaseDate: "2024-04-22",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "ボーナス/AT終了後は前兆（押忍モード/引き戻しモード）を確認してからヤメが基本。差枚1200枚以上の場合は特訓まで継続、引き戻しモードは対決敗北まで続行推奨",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "chonborista.com / p-world.co.jp / haienakun.com / slopachi-quest.com / note(たられば) 等",
    notes:
      "ゲーム数天井699G+αとボーナススルー回数天井（7回目で確定）の2種類。リセット時は押忍モード滞在＋スルー天井が6スルーに短縮。宗次郎ポイントという独自ポイント制を搭載",
  },
  {
    machineId: "izabancho_2025",
    machineName: "Lいざ！番長",
    maker: "大都技研",
    releaseDate: "2025-06-02",
    machineType: "AT機",
    hasCeiling: true,
    hasZone: true,
    hasOwnPoint: true,
    baseQuitTiming:
      "AT終了後はアイキャッチを確認してヤメが基本（強パターン出現時は続行）。上位AT終了後の「紫帯電」演出中は引き戻し（絶頂決戦）の期待が高いため必ずフォロー",
    lastConfirmedAt: "2026-07-06",
    sourceMemo: "slopachi-quest.com / chonborista.com / p-world.co.jp / note(のりへい) 等",
    notes:
      "ゲーム数天井999G+α（設定変更後600G+αに短縮）。100G/300Gにゾーンあり。御免ポイント（800G/900G到達で獲得）という独自ポイント制。上位AT『青頂ZBASH』と特化ゾーン『絶頂決戦』のループが特徴",
  },
];

export const machineRuleDetails: MachineRuleDetail[] = [
  // --- スマスロ北斗の拳 ---
  {
    machineId: "hokutonoken_2023",
    category: "天井",
    itemName: "AT間天井",
    thresholdRaw: "1268G+α（前兆最大32G）",
    triggerCondition: "AT間ゲーム数消化",
    benefit: "バトルボーナス当選（継続率優遇+北斗揃い期待度アップ）",
    targetMemo: "等価550G〜、56枚持ち570G〜が目安",
    notes: "",
  },
  {
    machineId: "hokutonoken_2023",
    category: "天井",
    itemName: "天井短縮抽選",
    thresholdRaw: "300G/777G/800Gで抽選",
    triggerCondition: "規定ゲーム到達時に抽選",
    benefit: "777G短縮時は北斗揃い確定",
    targetMemo: "",
    notes: "前回AT終了時の抽選ではなく規定G到達時の都度抽選",
  },
  {
    machineId: "hokutonoken_2023",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "800G+αに短縮",
    triggerCondition: "設定変更",
    benefit: "天井が468G短縮される一方、北斗揃い優遇等の恩恵は変わらず",
    targetMemo: "",
    notes: "リセット濃厚なホールでは積極的に狙い目",
  },
  {
    machineId: "hokutonoken_2023",
    category: "やめ時",
    itemName: "BB終了後の内部状態確認",
    thresholdRaw: "-",
    triggerCondition: "BB終了時",
    benefit: "天国/本前兆濃厚なら続行価値あり",
    targetMemo: "",
    notes: "天国/本前兆の示唆が確認できない場合は即ヤメ厳禁の例外に当たらない",
  },

  // --- スマスロ北斗の拳 転生の章2 ---
  {
    machineId: "hokutonoken_tensei2",
    category: "天井",
    itemName: "AT間天井（あべし）",
    thresholdRaw: "目安1473あべし以内でAT当選",
    triggerCondition: "あべし数消化（滞在モードにより変動）",
    benefit: "1473あべし以降の当選はATレベル3以上の恩恵",
    targetMemo: "等価でも500あべし未満は天井狙い非推奨",
    notes: "ゲーム数ではなく独自カウンター「あべし」で判断する点に注意",
  },
  {
    machineId: "hokutonoken_tensei2",
    category: "ゾーン",
    itemName: "193〜256あべしゾーン",
    thresholdRaw: "193〜256あべし",
    triggerCondition: "あべし数消化",
    benefit: "当選期待度が高いゾーン（設定5-6は256あべし以内当選率約...）",
    targetMemo: "滞在モード不問で押さえておきたいゾーン",
    notes: "",
  },
  {
    machineId: "hokutonoken_tensei2",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "最大1280あべしに短縮",
    triggerCondition: "設定変更",
    benefit: "天井あべし数の短縮",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "hokutonoken_tensei2",
    category: "やめ時",
    itemName: "AT終了後の残りカウンター確認",
    thresholdRaw: "-",
    triggerCondition: "AT終了時",
    benefit: "残りあべし数が多い場合は継続価値あり",
    targetMemo: "",
    notes: "AT終了後即ヤメが基本の機種のため、例外条件は限定的",
  },

  // --- スマスロ化物語 ---
  {
    machineId: "bakemonogatari_2025",
    category: "天井",
    itemName: "AT間天井",
    thresholdRaw: "1000G+α（実質1003G）",
    triggerCondition: "（俙）夢の時間ヲ終わらセルな終了後のゲーム数消化",
    benefit: "AT（俙時間）+倍倍チャンスストックのゲーム数消化確定",
    targetMemo: "通常650G〜が狙い目の目安",
    notes: "",
  },
  {
    machineId: "bakemonogatari_2025",
    category: "ゾーン",
    itemName: "100G/200G/300Gのゾーン",
    thresholdRaw: "100G・200G・300G",
    triggerCondition: "規定ゲーム到達",
    benefit: "CZ「解呪ノ儀」当選チャンス（300G時は設定1でも約40%）",
    targetMemo: "300G付近が最も期待できるゾーン",
    notes: "",
  },
  {
    machineId: "bakemonogatari_2025",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "600Gに短縮",
    triggerCondition: "設定変更",
    benefit: "天井ゲーム数の短縮（通常の4割引）",
    targetMemo: "",
    notes: "朝イチの保険として有効、ただし積極的に狙うほどではない",
  },
  {
    machineId: "bakemonogatari_2025",
    category: "やめ時",
    itemName: "解呪連モード確認",
    thresholdRaw: "ショート（平均2連）/ミドル（平均4連）/ロング",
    triggerCondition: "AT終了後 or CZ失敗後の一部で移行",
    benefit: "解呪ノ儀の連続当選チャンスが継続",
    targetMemo: "",
    notes:
      "AT中800枚/1500枚以上獲得時は50G以内の引き戻しで枚数引継ぎのため即ヤメ厳禁",
  },

  // --- L東京喰種 ---
  {
    machineId: "tokyoghoul_2025",
    category: "天井",
    itemName: "CZ間天井",
    thresholdRaw: "600G+α",
    triggerCondition: "CZ間ゲーム数消化",
    benefit: "CZ（レミニセンス/大喰いの利佳）当選相当の権利",
    targetMemo: "等価250G〜、5.6枚交換300G〜",
    notes: "",
  },
  {
    machineId: "tokyoghoul_2025",
    category: "天井",
    itemName: "AT間天井",
    thresholdRaw: "1200G+α",
    triggerCondition: "AT間ゲーム数消化（実ゲーム数、スイカ加算G含まず）",
    benefit: "AT（東京喰種咬）当選",
    targetMemo: "等価240G付近（液晶320G目安）〜が目安",
    notes: "",
  },
  {
    machineId: "tokyoghoul_2025",
    category: "リセット恩",
    itemName: "設定変更時CZ間天井短縮",
    thresholdRaw: "200G+αに短縮",
    triggerCondition: "設定変更",
    benefit: "CZ間天井の大幅短縮",
    targetMemo: "",
    notes: "リセット確認できた台は0Gでも期待値プラスとされる",
  },
  {
    machineId: "tokyoghoul_2025",
    category: "独自pt",
    itemName: "赫眼状態",
    thresholdRaw: "10G/20G/30G/50Gのいずれかで継続",
    triggerCondition: "下段リプレイ成立で発動（状況問わず）",
    benefit: "滞在中レア役確率が約1/2.6まで上昇",
    targetMemo: "",
    notes: "特化ゾーンと絡むと出玉が大きく加速",
  },

  // --- Lパチスロ炎炎ノ消防隊2 ---
  {
    machineId: "enenshouboutai2_2026",
    category: "天井",
    itemName: "ボーナス間天井",
    thresholdRaw: "850G+α",
    triggerCondition: "ボーナスゲーム数消化",
    benefit: "ボーナス当選",
    targetMemo: "800G〜が目安",
    notes: "",
  },
  {
    machineId: "enenshouboutai2_2026",
    category: "天井",
    itemName: "炎炎ループ間天井",
    thresholdRaw: "2000G+α",
    triggerCondition: "炎炎ループ間ゲーム数消化",
    benefit: "炎炎ループ（炎炎激闘/炎炎大戦等）当選",
    targetMemo: "1900G〜が目安",
    notes: "",
  },
  {
    machineId: "enenshouboutai2_2026",
    category: "独自pt",
    itemName: "伝導者の罠スルー天井",
    thresholdRaw: "5連続スルー",
    triggerCondition: "伝導者の罠を5回連続でスルー",
    benefit: "6回目のSPエピソードBONUS確定",
    targetMemo: "",
    notes: "4スルー目の台は必ず打ち切る価値あり",
  },
  {
    machineId: "enenshouboutai2_2026",
    category: "ゾーン",
    itemName: "モードE（119モード）",
    thresholdRaw: "88G+前兆（計119G）",
    triggerCondition: "ボーナス当選ごとに通常モード抽選",
    benefit: "119Gまでのボーナス当選濃厚",
    targetMemo: "アイキャッチで119示唆が出れば滞在期待大",
    notes: "",
  },
  {
    machineId: "enenshouboutai2_2026",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "ボーナス間650G+α/炎炎ループ間短縮",
    triggerCondition: "設定変更",
    benefit: "両天井とも短縮",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "enenshouboutai2_2026",
    category: "やめ時",
    itemName: "伝導者の罠/炎炎激闘後の潜伏確認",
    thresholdRaw: "88G+前兆 or 28G潜伏",
    triggerCondition: "初当たり（レギュラーボーナス）後 or 炎炎激闘失敗後",
    benefit: "炎炎激闘の潜伏・復活の可能性",
    targetMemo: "",
    notes: "即ヤメ厳禁。必ずG数を確認してからヤメ",
  },

  // --- スマスロ東京リベンジャーズ ---
  {
    machineId: "tokyorevengers_2025",
    category: "天井",
    itemName: "AT間天井",
    thresholdRaw: "1190G+α",
    triggerCondition: "AT間ゲーム数消化",
    benefit: "AT「東卍RUSH」当選",
    targetMemo: "等価450G〜、5.6枚交換540G〜",
    notes: "前兆を経由せず即告知",
  },
  {
    machineId: "tokyorevengers_2025",
    category: "独自pt",
    itemName: "周期ポイント",
    thresholdRaw: "1周期最大500pt、最大6周期到達で周期天井",
    triggerCondition: "規定ポイント到達",
    benefit: "ボーナス「東卍チャンス」またはAT「東卍RUSH」当選のチャンス",
    targetMemo: "周期狙いは1周期100pt〜、周期天井狙いは4周期480pt〜",
    notes: "ポイントはAT終了後も引き継がれる",
  },
  {
    machineId: "tokyorevengers_2025",
    category: "天井",
    itemName: "ボーナススルー回数天井",
    thresholdRaw: "東卍チャンス4スルー",
    triggerCondition: "ボーナスを規定回数連続でスルー",
    benefit: "AT当選率・獲得枚数がアップ",
    targetMemo: "3スルー〜が目安",
    notes: "",
  },
  {
    machineId: "tokyorevengers_2025",
    category: "リセット恩",
    itemName: "設定変更時AT間天井短縮",
    thresholdRaw: "900G+αに短縮",
    triggerCondition: "設定変更",
    benefit: "AT間天井の短縮",
    targetMemo: "",
    notes: "ボーナスを挟んでもAT間天井は引き継がれる",
  },
  {
    machineId: "tokyorevengers_2025",
    category: "やめ時",
    itemName: "サブ液晶セリフ確認",
    thresholdRaw: "-",
    triggerCondition: "AT/ボーナス終了後",
    benefit: "赤セリフなら周期当選まで続行価値あり、マイキー青セリフなら天国の可能性",
    targetMemo: "",
    notes: "上位AT後やリベンジチャンス後は周期ポイントのノイズが消えるまでフォロー推奨",
  },

  // --- スマスロ新鬼武者3 ---
  {
    machineId: "shinonimusya3_2025",
    category: "天井",
    itemName: "ゲーム数天井",
    thresholdRaw: "1000G+α",
    triggerCondition: "AT間ゲーム数消化",
    benefit: "AT「蒼剣RUSH」当選",
    targetMemo: "",
    notes: "設定変更後も1000Gで変わらず（周期天井側が短縮される仕様）",
  },
  {
    machineId: "shinonimusya3_2025",
    category: "独自pt",
    itemName: "周期天井（バッサリポイント）",
    thresholdRaw: "最大666BP到達で鬼モードへ、最大6周期消化で天井",
    triggerCondition: "規定バッサリポイント（BP）到達",
    benefit: "AT当選のチャンス（鬼モードで告知）",
    targetMemo: "",
    notes: "555BP以上選択時は次回222BP以内に鬼モード移行",
  },
  {
    machineId: "shinonimusya3_2025",
    category: "リセット恩",
    itemName: "設定変更時周期短縮",
    thresholdRaw: "最大4周期に短縮、1周期目は222pt以内",
    triggerCondition: "設定変更",
    benefit: "早い段階でのAT当選に期待",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "shinonimusya3_2025",
    category: "ゾーン",
    itemName: "350G/550Gゾーン",
    thresholdRaw: "350G・550G",
    triggerCondition: "規定ゲーム数到達",
    benefit: "百鬼モード移行のチャンス",
    targetMemo: "",
    notes: "前兆（黒モヤ）は357〜360G付近で発生することが多い",
  },
  {
    machineId: "shinonimusya3_2025",
    category: "やめ時",
    itemName: "上位AT後のフォロー確認",
    thresholdRaw: "-",
    triggerCondition: "上位AT「真蒼剣RUSH」終了後",
    benefit: "次回1周期目のAT当選が濃厚",
    targetMemo: "",
    notes: "即ヤメ厳禁の例外に該当。必ず1周期分は様子を見る",
  },

  // --- Lパチスロ 機動戦士ガンダムSEED ---
  {
    machineId: "gundamseed_2025",
    category: "天井",
    itemName: "CZ天井",
    thresholdRaw: "777G",
    triggerCondition: "通常時ゲーム数消化",
    benefit: "CZ「ストライクアタック」当選",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "gundamseed_2025",
    category: "天井",
    itemName: "ST天井（AT間天井）",
    thresholdRaw: "1280G",
    triggerCondition: "ST間ゲーム数消化",
    benefit: "BAR BIG当選",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "gundamseed_2025",
    category: "リセット恩",
    itemName: "設定変更・ST駆け抜け時の天井短縮",
    thresholdRaw: "750Gに短縮",
    triggerCondition: "設定変更 または ST駆け抜け",
    benefit: "天井ゲーム数の大幅短縮",
    targetMemo: "",
    notes: "リセット時は内部的にゲーム数がランダム加算されるため前兆タイミングのズレのみで据え置き確定とは言えない",
  },
  {
    machineId: "gundamseed_2025",
    category: "独自pt",
    itemName: "宿命ポイント",
    thresholdRaw: "ボーナス中MAX到達",
    triggerCondition: "ボーナス中のリプレイ・3枚ベル・レア役成立",
    benefit: "宿命ゾーン（上位ATを賭けたCZ）突入",
    targetMemo: "",
    notes: "ポイントはST継続失敗まで持ち越される",
  },
  {
    machineId: "gundamseed_2025",
    category: "やめ時",
    itemName: "宿命ポイント残量の確認",
    thresholdRaw: "-",
    triggerCondition: "ボーナス終了時",
    benefit: "宿命ポイントが貯まっている場合は宿命ゾーン到達まで継続価値あり",
    targetMemo: "",
    notes: "即ヤメ厳禁の例外に該当する可能性あり",
  },

  // --- スマスロ マギアレコード 魔法少女まどか☆マギカ外伝 ---
  {
    machineId: "magireco_2025",
    category: "天井",
    itemName: "ボーナス間天井",
    thresholdRaw: "950pt+α",
    triggerCondition: "規定ポイント到達",
    benefit: "ボーナス当選",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "magireco_2025",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "600〜699pt+αに短縮",
    triggerCondition: "設定変更",
    benefit: "ボーナス間天井の大幅短縮",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "magireco_2025",
    category: "ゾーン",
    itemName: "200pt/400pt/600ptゾーン",
    thresholdRaw: "200pt・400pt・600pt",
    triggerCondition: "規定ポイント到達",
    benefit: "ボーナス当選のチャンスが上昇",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "magireco_2025",
    category: "独自pt",
    itemName: "穢れポイント",
    thresholdRaw: "100pt蓄積",
    triggerCondition: "プレイヤーに不利な事象が発生した際に加算",
    benefit: "ボーナス当選時にエピソードボーナスまたはアリナミュージアムへ発展",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "magireco_2025",
    category: "やめ時",
    itemName: "ボーナス/AT終了後の基本ヤメ",
    thresholdRaw: "-",
    triggerCondition: "ボーナス/AT終了時",
    benefit: "-",
    targetMemo: "",
    notes: "基本1Gヤメ。ただしみたまボーナス終了後は平均15Gヤメが目安",
  },

  // --- スマスロ ミリオンゴッド-神々の軌跡- ---
  {
    machineId: "milliongod_kiseki_2026",
    category: "天井",
    itemName: "ゲーム数天井",
    thresholdRaw: "510G・1000G・1480Gのいずれか",
    triggerCondition: "通常時ゲーム数消化",
    benefit: "AT「ゴッドゲーム(GG)」当選。天井到達時はループストックD（80%ループ）とZ-ZONE獲得の割合が高い",
    targetMemo: "",
    notes: "天井ストッパーはなし",
  },
  {
    machineId: "milliongod_kiseki_2026",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "1/3以上の割合で510Gか1000Gに短縮",
    triggerCondition: "設定変更",
    benefit: "天井ゲーム数の短縮",
    targetMemo: "",
    notes: "全設定共通の振り分け（前作「神々の凱旋」とは異なる仕様）",
  },
  {
    machineId: "milliongod_kiseki_2026",
    category: "ゾーン",
    itemName: "Z-ZONE",
    thresholdRaw: "-",
    triggerCondition: "ガイアステージ中の0図柄揃い等",
    benefit: "上乗せ連鎖ゾーン「Z-GAME」への移行チャンス",
    targetMemo: "",
    notes: "奇数設定の方が昇格率が優遇されている",
  },
  {
    machineId: "milliongod_kiseki_2026",
    category: "やめ時",
    itemName: "GG終了後の引き戻し確認",
    thresholdRaw: "36G以内",
    triggerCondition: "AT「ゴッドゲーム(GG)」終了後",
    benefit: "GG引き戻しの可能性",
    targetMemo: "",
    notes: "即ヤメ厳禁。必ずフォローしてからヤメる",
  },

  // --- L虚構推理 ---
  {
    machineId: "kyokosuiri_2026",
    category: "天井",
    itemName: "ゲーム数天井",
    thresholdRaw: "1000G",
    triggerCondition: "通常時（虚構真偽間）ゲーム数消化",
    benefit: "ボーナス当選＋雪女ストック1個以上獲得",
    targetMemo: "等価450G〜、5.6枚持ちメダル450G〜、5.6枚現金590G〜",
    notes: "300G以降は設定差が大きい",
  },
  {
    machineId: "kyokosuiri_2026",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "300Gまたは700Gに短縮",
    triggerCondition: "設定変更",
    benefit: "天井ゲーム数の短縮（高確スタート約50%）",
    targetMemo: "",
    notes: "電源OFF/ONの場合は天井・内部モードとも引き継ぎ",
  },
  {
    machineId: "kyokosuiri_2026",
    category: "ゾーン",
    itemName: "100G毎のCZ抽選",
    thresholdRaw: "100G毎",
    triggerCondition: "規定ゲーム数消化",
    benefit: "CZ「鋼人七瀬攻略議会」当選のチャンス",
    targetMemo: "",
    notes: "CZ間300G以上ハマると以降100G毎のCZ当選率が約52%にアップ",
  },
  {
    machineId: "kyokosuiri_2026",
    category: "独自pt",
    itemName: "虚構連モード",
    thresholdRaw: "ショート/ミドル/ロングの3種類",
    triggerCondition: "ボーナス当選後に必ず移行",
    benefit: "滞在中はボーナス抽選が優遇される（ロングは継続率約95%）",
    targetMemo: "",
    notes: "上位AT「輪廻転生」の期待枚数は約3,500枚以上",
  },
  {
    machineId: "kyokosuiri_2026",
    category: "やめ時",
    itemName: "虚構連モード転落確認",
    thresholdRaw: "50G",
    triggerCondition: "ボーナス後の虚構連モード中",
    benefit: "転落せず50G経過で虚構真偽突入濃厚",
    targetMemo: "",
    notes: "見た目で転落タイミングが分からないため50Gを目安にフォロー推奨",
  },

  // --- スマスロ攻殻機動隊 ---
  {
    machineId: "koukakukidoutai_2026",
    category: "天井",
    itemName: "CZ間天井",
    thresholdRaw: "550G+α",
    triggerCondition: "通常時ゲーム数消化",
    benefit: "CZ当選",
    targetMemo: "等価300G〜（白の境界失敗後は170G〜）",
    notes: "",
  },
  {
    machineId: "koukakukidoutai_2026",
    category: "天井",
    itemName: "AT間天井",
    thresholdRaw: "999G+α",
    triggerCondition: "AT間ゲーム数消化",
    benefit: "AT当選",
    targetMemo: "等価650G〜",
    notes: "",
  },
  {
    machineId: "koukakukidoutai_2026",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "CZ間350G+α・AT間699G+αに短縮",
    triggerCondition: "設定変更",
    benefit: "天井短縮に加えCZ当選まで殲滅テーブル2以上が選択される",
    targetMemo: "",
    notes: "200GでのタチコマCZ当選率が約50%と優遇。設定1でも機械割100%超",
  },
  {
    machineId: "koukakukidoutai_2026",
    category: "独自pt",
    itemName: "殲滅ポイント",
    thresholdRaw: "150pt到達",
    triggerCondition: "通常ゲーム消化・レア役成立で加算",
    benefit: "殲滅ゾーン突入（CZ突入抽選のようなモード）",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "koukakukidoutai_2026",
    category: "やめ時",
    itemName: "通常Dモード時のフォロー",
    thresholdRaw: "150G+α",
    triggerCondition: "AT終了後、約50%で通常D（CZ天井150G）へ移行",
    benefit: "150G+αでCZ当選のチャンス",
    targetMemo: "",
    notes: "白の境界失敗後はCZ天井400G+αまで継続推奨",
  },

  // --- Lパチスロ 機動戦士ガンダムユニコーン 覚醒DRIVE ---
  {
    machineId: "gundam_unicorn_kakusei_2026",
    category: "天井",
    itemName: "CZ天井",
    thresholdRaw: "800G+α（実ゲーム数）",
    triggerCondition: "通常時ゲーム数消化",
    benefit: "CZ「彗星決戦」当選",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "gundam_unicorn_kakusei_2026",
    category: "天井",
    itemName: "AT天井",
    thresholdRaw: "1400G+α（液晶ゲーム数）",
    triggerCondition: "AT間ゲーム数消化",
    benefit: "AT当選",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "gundam_unicorn_kakusei_2026",
    category: "天井",
    itemName: "CZ6スルー天井",
    thresholdRaw: "CZ6回連続スルー",
    triggerCondition: "CZ「彗星決戦」を6回連続でスルー",
    benefit: "7回目のCZは経由せず直接ボーナス（AT）当選",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "gundam_unicorn_kakusei_2026",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "CZ400G+α・AT1000G+αに短縮",
    triggerCondition: "設定変更",
    benefit: "天井ゲーム数の大幅短縮",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "gundam_unicorn_kakusei_2026",
    category: "ゾーン",
    itemName: "100Gゾーン",
    thresholdRaw: "100G",
    triggerCondition: "液晶ゲーム数基準で100G到達",
    benefit: "全シナリオ共通で超高確またはCZ濃厚",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "gundam_unicorn_kakusei_2026",
    category: "やめ時",
    itemName: "上位AT終了後のスタンバイレベル確認",
    thresholdRaw: "-",
    triggerCondition: "上位AT『覚醒HYPER -Over The Rainbow-』終了後（覚醒の光失敗後）",
    benefit: "スタンバイレベルMAXが引き継がれ、次回リプレイでCZ以上当選が確約",
    targetMemo: "",
    notes: "即ヤメ厳禁の代表例",
  },

  // --- L吉宗 ---
  {
    machineId: "yoshimune_2025",
    category: "天井",
    itemName: "ボーナス間天井",
    thresholdRaw: "999G",
    triggerCondition: "通常時ゲーム数消化",
    benefit: "ボーナス当選",
    targetMemo: "等価580G〜、5.6枚現金670G〜",
    notes: "レア役成立時はゲーム数カウンタの加算抽選もあり",
  },
  {
    machineId: "yoshimune_2025",
    category: "ゾーン",
    itemName: "天国モード天井",
    thresholdRaw: "193G",
    triggerCondition: "ボーナス終了後、天国モードへ移行した場合",
    benefit: "約30%は100G以内でボーナス当選",
    targetMemo: "ボーナス1G連後は0G〜、390〜465Gのゾーンも狙い目",
    notes: "",
  },
  {
    machineId: "yoshimune_2025",
    category: "独自pt",
    itemName: "裏鷹狩り",
    thresholdRaw: "1G連2回獲得",
    triggerCondition: "ボーナス中の1G連を2回獲得",
    benefit: "期待枚数約3600枚の裏鷹狩りへ移行",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "yoshimune_2025",
    category: "やめ時",
    itemName: "天国示唆の確認",
    thresholdRaw: "-",
    triggerCondition: "鷹狩りからのボーナス当選・松からのボーナス当選・裏鷹狩り失敗後",
    benefit: "天国モード濃厚",
    targetMemo: "",
    notes: "即ヤメ厳禁。193Gまではフォロー推奨",
  },

  // --- Lパチスロ 革命機ヴァルヴレイヴ2 ---
  {
    machineId: "valvrave2_2025",
    category: "天井",
    itemName: "ボーナス・AT間天井",
    thresholdRaw: "1500G+α",
    triggerCondition: "ボーナス・AT間ゲーム数消化",
    benefit: "革命ボーナス/決戦ボーナス/革命ラッシュが均等(33.3%ずつ)に選択",
    targetMemo: "不問950G〜",
    notes: "",
  },
  {
    machineId: "valvrave2_2025",
    category: "天井",
    itemName: "CZ間天井",
    thresholdRaw: "999G+α",
    triggerCondition: "CZ間ゲーム数消化",
    benefit: "CZ「ドルシア攻防戦」当選",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "valvrave2_2025",
    category: "天井",
    itemName: "決戦ボーナススルー回数天井",
    thresholdRaw: "決戦0スルー〜",
    triggerCondition: "決戦ボーナスを規定回数連続でスルー",
    benefit: "天井狙いの狙い目が浅くなる",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "valvrave2_2025",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "1000G+αに短縮",
    triggerCondition: "設定変更",
    benefit: "ボーナス・AT間天井の短縮",
    targetMemo: "不問480G〜",
    notes: "",
  },
  {
    machineId: "valvrave2_2025",
    category: "独自pt",
    itemName: "周期ポイント",
    thresholdRaw: "毎ゲーム1pt以上、最大600ptで1周期、最大6周期",
    triggerCondition: "リプレイ/ベルは5pt以上、レア役は10pt以上獲得",
    benefit: "周期到達でCZ「ドルシア攻防戦」の当否告知",
    targetMemo: "",
    notes: "設定変更後は最大3周期に短縮",
  },
  {
    machineId: "valvrave2_2025",
    category: "やめ時",
    itemName: "AT終了後の引き戻し確認",
    thresholdRaw: "66G",
    triggerCondition: "AT「(超)革命RUSH」終了後",
    benefit: "引き戻しの可能性（革命ボーナス後約9%、決戦ボーナス後約6%）",
    targetMemo: "",
    notes: "引き戻し率自体は高くないため、必須のフォローというよりは任意判断",
  },

  // --- スマスロスーパーブラックジャック ---
  {
    machineId: "superblackjack_2025",
    category: "天井",
    itemName: "ゲーム数天井",
    thresholdRaw: "999G+α",
    triggerCondition: "通常時ゲーム数消化",
    benefit: "BIG当選",
    targetMemo: "等価570G〜",
    notes: "",
  },
  {
    machineId: "superblackjack_2025",
    category: "リセット恩",
    itemName: "設定変更・リオチャンス非当選時の天井短縮",
    thresholdRaw: "666G+αに短縮",
    triggerCondition: "設定変更、または初当りBIG後のリオチャンス高確で非当選のまま転落",
    benefit: "天井ゲーム数の短縮",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "superblackjack_2025",
    category: "天井",
    itemName: "RBスルー回数天井",
    thresholdRaw: "RB4連続",
    triggerCondition: "初当りRBが4連続",
    benefit: "次回初当りで必ずBIG当選",
    targetMemo: "REGスルー回数狙いは3スルー〜",
    notes: "RB当選時は通常時ゲーム数天井を引き継ぐ",
  },
  {
    machineId: "superblackjack_2025",
    category: "独自pt",
    itemName: "スイカ回数天井",
    thresholdRaw: "規定回数（設定変更後は優遇）",
    triggerCondition: "同一有利区間内でスイカが規定回数成立",
    benefit: "ストックタイム直撃",
    targetMemo: "リオチャンススルー後は250G〜から狙い目",
    notes: "",
  },
  {
    machineId: "superblackjack_2025",
    category: "やめ時",
    itemName: "BIG終了後のリオチャンス高確確認",
    thresholdRaw: "30G",
    triggerCondition: "BIG終了後",
    benefit: "最低30G間はリオチャンス高確率に滞在",
    targetMemo: "",
    notes: "即ヤメ厳禁。30G以降は示唆演出を頼りに判断",
  },

  // --- スロット ソードアート・オンラインII ---
  {
    machineId: "sao2_2026",
    category: "天井",
    itemName: "AT間天井",
    thresholdRaw: "1200G",
    triggerCondition: "AT間ゲーム数消化",
    benefit: "AT当選",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "sao2_2026",
    category: "天井",
    itemName: "CZ間天井",
    thresholdRaw: "499G+α（実ゲーム）または液晶ゲーム数800G",
    triggerCondition: "CZ間ゲーム数消化",
    benefit: "CZ「スコードロンバトル」当選",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "sao2_2026",
    category: "リセット恩",
    itemName: "設定変更・上位CZ失敗後の天井短縮",
    thresholdRaw: "256G+αに短縮",
    triggerCondition: "設定変更、または初回の上位CZ失敗後",
    benefit: "CZ間天井の大幅短縮",
    targetMemo: "",
    notes: "上位AT後の上位CZは対象外",
  },
  {
    machineId: "sao2_2026",
    category: "ゾーン",
    itemName: "内部モード別の液晶ゲーム数天井",
    thresholdRaw: "通常A/B 800G・通常C 650G・通常D 350G・天国 100G",
    triggerCondition: "内部モードごとの規定液晶ゲーム数到達",
    benefit: "CZ当選（天国移行までモードダウンなし）",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "sao2_2026",
    category: "やめ時",
    itemName: "AT終了後の引き戻しゾーン確認",
    thresholdRaw: "50G",
    triggerCondition: "AT終了後",
    benefit: "引き戻しゾーン中の当選チャンス",
    targetMemo: "",
    notes: "50G消化してから判断するのが基本",
  },

  // --- スマスロ 甲鉄城のカバネリ 海門決戦 ---
  {
    machineId: "kabaneri2_2026",
    category: "天井",
    itemName: "ゲーム数天井",
    thresholdRaw: "996G+α",
    triggerCondition: "通常時ゲーム数消化",
    benefit: "エピソードボーナス当選（消化後ST突入濃厚）",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "kabaneri2_2026",
    category: "独自pt",
    itemName: "周期（カバネポイント）",
    thresholdRaw: "1周期目150G・2周期目300Gで自動到達、最大6周期",
    triggerCondition: "規定カバネポイント到達（1〜2周期目はポイント不足でも規定G数で到達）",
    benefit: "前兆演出を経てボーナス当否告知",
    targetMemo: "1周期目消化で130G、2周期目消化で270G付近が狙い目",
    notes: "3周期目以降はポイントが溜まらないと周期が進まない",
  },
  {
    machineId: "kabaneri2_2026",
    category: "リセット恩",
    itemName: "設定変更・ST駆け抜け・景之ST後の天井短縮",
    thresholdRaw: "596G+α・周期天井は最大4周期に短縮",
    triggerCondition: "設定変更、ST駆け抜け、または景之ST終了後",
    benefit: "天井の大幅短縮（等価なら0Gから期待値プラス）",
    targetMemo: "",
    notes: "サブ液晶背景が桜/海門城に変化していれば該当",
  },
  {
    machineId: "kabaneri2_2026",
    category: "やめ時",
    itemName: "ST終了後のポイント・示唆確認",
    thresholdRaw: "-",
    triggerCondition: "ST終了時",
    benefit: "カバネポイントが溜まっていなければ即ヤメでよい",
    targetMemo: "",
    notes: "サブ液晶背景の桜/海門城表示があればフォロー推奨",
  },

  // --- パチスロ からくりサーカス ---
  {
    machineId: "karakurisaakasu_2023",
    category: "天井",
    itemName: "ゲーム数天井",
    thresholdRaw: "1200G",
    triggerCondition: "通常時ゲーム数消化",
    benefit: "CZ「機械仕掛けの神」以上当選",
    targetMemo: "0G〜（スルー回数が増えるごとに狙い目が浅くなる）",
    notes: "",
  },
  {
    machineId: "karakurisaakasu_2023",
    category: "リセット恩",
    itemName: "前回当選G数による天井短縮",
    thresholdRaw: "最大300Gに短縮",
    triggerCondition: "前回の当選が液晶1100G以上（データカウンタ目安800G以上）",
    benefit: "次回天井ゲーム数の大幅短縮",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "karakurisaakasu_2023",
    category: "ゾーン",
    itemName: "天国モード天井",
    thresholdRaw: "100G",
    triggerCondition: "上位AT「超からくりサーカス」終了後、約40%で天国移行",
    benefit: "100G以内でCZ当選",
    targetMemo: "",
    notes: "データカウンターの文字色がピンクなら天国濃厚",
  },
  {
    machineId: "karakurisaakasu_2023",
    category: "やめ時",
    itemName: "幕間チャンス後のワイプ確認",
    thresholdRaw: "1G",
    triggerCondition: "幕間チャンス終了後",
    benefit: "ワイプ画面で規定ゲーム数の示唆を確認できる",
    targetMemo: "",
    notes: "しろがね（シルエット/アップ）示唆が出ている場合はCZ当選までフォロー",
  },

  // --- スマスロ キン肉マン 7人の悪魔超人編 ---
  {
    machineId: "kinnikuman_7akuma_2023",
    category: "天井",
    itemName: "超人パワー天井",
    thresholdRaw: "1000万パワー（実ゲーム数平均約600G）",
    triggerCondition: "通常時1Gあたり1万パワー獲得での累積、モードにより変動",
    benefit: "AT「7人の悪魔超人」当選",
    targetMemo: "等価660G〜",
    notes: "モードA1000G・モードB900G・チャンス300Gが目安の天井ゲーム数",
  },
  {
    machineId: "kinnikuman_7akuma_2023",
    category: "リセット恩",
    itemName: "設定変更時チャンスモード優遇",
    thresholdRaw: "チャンスモード選択率約25%",
    triggerCondition: "設定変更",
    benefit: "天井ゲーム数が浅いチャンスモードへの移行優遇",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "kinnikuman_7akuma_2023",
    category: "独自pt",
    itemName: "超人パワー上乗せゾーン",
    thresholdRaw: "正義超人チャレンジ（平均144万パワー）/正義超人アタック（平均1029万パワー）",
    triggerCondition: "AT中の抽選で突入",
    benefit: "超人パワーの大量獲得（天井到達を早める）",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "kinnikuman_7akuma_2023",
    category: "やめ時",
    itemName: "AT終了後の即ヤメ判断",
    thresholdRaw: "-",
    triggerCondition: "AT終了後、モード示唆等がない場合",
    benefit: "-",
    targetMemo: "",
    notes: "天井到達率が高くゾーンでの当選率上昇もほぼ無いため、原則即ヤメでよい機種",
  },

  // --- スマスロ ゴッドイーター リザレクション ---
  {
    machineId: "godeater_resurrection_2024",
    category: "天井",
    itemName: "ゲーム数天井",
    thresholdRaw: "1000G+α（100/200/300/450/600/750/1000Gの7種振り分け）",
    triggerCondition: "通常時ゲーム数消化",
    benefit: "AT「アラガミバースト」確定",
    targetMemo: "580G〜",
    notes: "",
  },
  {
    machineId: "godeater_resurrection_2024",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "600G+αに短縮",
    triggerCondition: "設定変更",
    benefit: "天井ゲーム数の短縮",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "godeater_resurrection_2024",
    category: "ゾーン",
    itemName: "100G/300Gゾーン",
    thresholdRaw: "100G・300G",
    triggerCondition: "規定ゲーム数到達",
    benefit: "CZ当選率アップ",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "godeater_resurrection_2024",
    category: "やめ時",
    itemName: "AT終了後の状態確認",
    thresholdRaw: "1G",
    triggerCondition: "AT終了後",
    benefit: "バカンスモード移行時は100G+αフォロー",
    targetMemo: "",
    notes: "逆鱗ハンニバル討伐戦敗北時・有利区間差枚+1000枚以上時も即ヤメ厳禁",
  },

  // --- L主役は銭形5 ---
  {
    machineId: "zenigata5_2025",
    category: "天井",
    itemName: "ゲーム数天井",
    thresholdRaw: "1250G+α",
    triggerCondition: "通常時ゲーム数消化",
    benefit: "ボーナス当選（50%で不二子デカタイム突入）",
    targetMemo: "",
    notes: "1000G以上のハマり後の当選は次回モードB以上濃厚",
  },
  {
    machineId: "zenigata5_2025",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "850G+αに短縮",
    triggerCondition: "設定変更",
    benefit: "天井ゲーム数の短縮",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "zenigata5_2025",
    category: "ゾーン",
    itemName: "150G/350G/550Gゾーン",
    thresholdRaw: "150G・350G・550G",
    triggerCondition: "規定ゲーム数到達",
    benefit: "前兆ステージ「ゼニガタイム」移行のチャンス",
    targetMemo: "液晶100G/280G/480G付近から狙い目",
    notes: "",
  },
  {
    machineId: "zenigata5_2025",
    category: "独自pt",
    itemName: "捜査ポイント",
    thresholdRaw: "0pt到達",
    triggerCondition: "毎ゲーム成立役に応じて1pt以上減算",
    benefit: "CZ「逮捕チャレンジ」当選",
    targetMemo: "操作pt100pt以下の台も狙い目",
    notes: "",
  },
  {
    machineId: "zenigata5_2025",
    category: "やめ時",
    itemName: "ST終了後の引き戻し確認",
    thresholdRaw: "80G",
    triggerCondition: "ST終了後",
    benefit: "80G以内のボーナス当選で前回逮捕状況を引き継いで復帰",
    targetMemo: "",
    notes: "",
  },

  // --- スマスロ 聖闘士星矢 海皇覚醒 CUSTOM EDITION ---
  {
    machineId: "seiya_kaiou_2024",
    category: "天井",
    itemName: "ゲーム数天井",
    thresholdRaw: "999G（600Gに期待度50%の仮天井あり）",
    triggerCondition: "通常時ゲーム数消化",
    benefit: "CZ「海将軍激闘」当選",
    targetMemo: "",
    notes: "仮天井をスルーしてもコイン持ちが約46回転にアップ",
  },
  {
    machineId: "seiya_kaiou_2024",
    category: "天井",
    itemName: "GBスルー天井",
    thresholdRaw: "8スルー",
    triggerCondition: "CZ「海将軍激闘」を8回連続でスルー",
    benefit: "9回目のCZでAT確定",
    targetMemo: "",
    notes: "2スルー（3回目）時点でも振り分けあり",
  },
  {
    machineId: "seiya_kaiou_2024",
    category: "リセット恩",
    itemName: "設定変更・SR終了時の天井短縮",
    thresholdRaw: "536G+αに短縮",
    triggerCondition: "設定変更、またはSR（聖闘士RUSH）終了時",
    benefit: "天井ゲーム数の短縮",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "seiya_kaiou_2024",
    category: "独自pt",
    itemName: "不屈ポイント",
    thresholdRaw: "50pt到達（MAX）",
    triggerCondition: "通常時の蓄積",
    benefit: "次回CZ「海将軍激闘」の突破が確定",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "seiya_kaiou_2024",
    category: "やめ時",
    itemName: "CZ/AT終了後の前兆確認",
    thresholdRaw: "5G",
    triggerCondition: "CZ/AT終了後",
    benefit: "-",
    targetMemo: "",
    notes: "継続率70%以上のCZ失敗時・特定終了画面示唆時は即ヤメ厳禁",
  },

  // --- スマスロ鉄拳6 ---
  {
    machineId: "tekken6_2026",
    category: "天井",
    itemName: "鉄拳ポイント天井",
    thresholdRaw: "最大500pt+α（モードにより変動）",
    triggerCondition: "毎ゲーム1pt以上、レア役成立時1〜100pt加算",
    benefit: "ボーナスまたはデビルゾーン当選",
    targetMemo: "",
    notes: "規定ポイント到達後は前兆「鉄拳ゾーン」でバトル演出により当落告知",
  },
  {
    machineId: "tekken6_2026",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "最大500pt+αに短縮（設定変更モード）",
    triggerCondition: "設定変更",
    benefit: "天井ポイントの短縮",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "tekken6_2026",
    category: "ゾーン",
    itemName: "100pt/300pt/500ptゾーン",
    thresholdRaw: "100pt・300pt・500pt",
    triggerCondition: "規定ポイント到達",
    benefit: "デビルモード以外の全モードで300ptが特に濃いゾーン",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "tekken6_2026",
    category: "やめ時",
    itemName: "AT終了後の引き戻し確認",
    thresholdRaw: "99pt以内",
    triggerCondition: "AT終了後",
    benefit: "引き戻し当選でAT「鉄拳RUSH」再突入",
    targetMemo: "",
    notes: "引き戻し中はリール周辺UIが赤く光って示唆",
  },

  // --- スマスロ とある科学の超電磁砲2 ---
  {
    machineId: "toaru_railgun2_2025",
    category: "天井",
    itemName: "ゲーム数天井",
    thresholdRaw: "999G+α",
    triggerCondition: "通常時ゲーム数消化",
    benefit: "超電磁砲コイン揃い＋前兆を経てAT「超電磁砲DRIVE」当選",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "toaru_railgun2_2025",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "699G+αに短縮",
    triggerCondition: "設定変更",
    benefit: "天井ゲーム数の短縮",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "toaru_railgun2_2025",
    category: "ゾーン",
    itemName: "モード別天井・500Gゾーン",
    thresholdRaw: "通常A999G/B・C699G/D299G/E199G、AT後500G",
    triggerCondition: "滞在モードごとの規定ゲーム数、またはAT後の500G到達",
    benefit: "モードが浅いほど早い天井。500GゾーンはAT後期待度約40%",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "toaru_railgun2_2025",
    category: "やめ時",
    itemName: "AT終了後の100Gゾーン確認",
    thresholdRaw: "100G",
    triggerCondition: "AT終了後",
    benefit: "約25%でCZ天井に該当",
    targetMemo: "",
    notes: "高確状態（コインが成立しやすい）ならフォロー推奨",
  },

  // --- L押忍！番長4 ---
  {
    machineId: "osubancho4_2024",
    category: "天井",
    itemName: "ゲーム数天井",
    thresholdRaw: "699G+α",
    triggerCondition: "ボーナス間ゲーム数消化",
    benefit: "ボーナス当選",
    targetMemo: "400G〜",
    notes: "",
  },
  {
    machineId: "osubancho4_2024",
    category: "天井",
    itemName: "ボーナススルー回数天井",
    thresholdRaw: "7回目のボーナス",
    triggerCondition: "AT非当選のままボーナスを規定回数連続で通過",
    benefit: "AT確定",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "osubancho4_2024",
    category: "リセット恩",
    itemName: "設定変更時の押忍モード＆スルー天井短縮",
    thresholdRaw: "スルー天井6スルー（7回目で確定）",
    triggerCondition: "設定変更",
    benefit: "押忍モード滞在（特訓間最大149G）＋スルー天井の短縮",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "osubancho4_2024",
    category: "独自pt",
    itemName: "宗次郎ポイント",
    thresholdRaw: "規定ポイント到達",
    triggerCondition: "特訓経由の対決敗北時等に獲得",
    benefit: "次の特訓が宗次郎特訓（上位特訓）に昇格",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "osubancho4_2024",
    category: "やめ時",
    itemName: "ボーナス/AT終了後の前兆確認",
    thresholdRaw: "-",
    triggerCondition: "ボーナス/AT終了後",
    benefit: "押忍モード/引き戻しモード滞在時は続行価値あり",
    targetMemo: "",
    notes: "差枚1200枚以上の場合は特訓まで、AT後の引き戻しモードは対決敗北まで続行推奨",
  },

  // --- Lいざ！番長 ---
  {
    machineId: "izabancho_2025",
    category: "天井",
    itemName: "ゲーム数天井",
    thresholdRaw: "999G+α",
    triggerCondition: "通常時ゲーム数消化",
    benefit: "AT当選",
    targetMemo: "等価470G〜、5.6枚現金560G〜",
    notes: "",
  },
  {
    machineId: "izabancho_2025",
    category: "リセット恩",
    itemName: "設定変更時天井短縮",
    thresholdRaw: "600G+αに短縮",
    triggerCondition: "設定変更",
    benefit: "天井ゲーム数の短縮。チャンスA以上濃厚＋天国移行率25%",
    targetMemo: "180G〜",
    notes: "",
  },
  {
    machineId: "izabancho_2025",
    category: "ゾーン",
    itemName: "100G/300Gゾーン",
    thresholdRaw: "100G・300G",
    triggerCondition: "規定ゲーム数到達",
    benefit: "どのモードでもチャンスとなるゾーン",
    targetMemo: "",
    notes: "",
  },
  {
    machineId: "izabancho_2025",
    category: "独自pt",
    itemName: "御免ポイント",
    thresholdRaw: "800G/900G到達",
    triggerCondition: "ゲーム数ハマり・対決敗北・AT終了時等",
    benefit: "刀ポイントMAXでCZ「刺客ゾーン」当選",
    targetMemo: "刀メーター70pt〜MAXの前兆終了まで",
    notes: "",
  },
  {
    machineId: "izabancho_2025",
    category: "やめ時",
    itemName: "アイキャッチ・上位AT後の帯電確認",
    thresholdRaw: "-",
    triggerCondition: "AT終了後（特に上位AT終了後）",
    benefit: "「紫帯電」演出が続く間は絶頂決戦への引き戻し期待大",
    targetMemo: "",
    notes: "上位AT後の即ヤメ厳禁パターン",
  },
];

export function getMachineMaster(machineId: string): MachineMaster | undefined {
  return machineMasters.find((m) => m.machineId === machineId);
}

export function getRuleDetails(machineId: string): MachineRuleDetail[] {
  return machineRuleDetails.filter((r) => r.machineId === machineId);
}
